### ISSUE TITLE
Ni et al 2017

### ISSUE THREAD

**Issue by MichaelClerx** [PMR2/models.physiomeproject.org#49]
Current exposure: https://models.physiomeproject.org/e/807

There is a nicer exposure for this (https://models.physiomeproject.org/e/807), but the Electrophysiology page links instead to https://models.physiomeproject.org/e/807/ni_2017.cellml/view

Requested action: Tell me how to fix this?

**Comment by metatoaster** [comment]
The "Electrophysiology page" (along with all other CellML category listing pages) links to individual exposure files and never the top level exposure object, as individual exposure files can unambiguously represent a single model file while the top level exposure object may contain other unrelated content.

If the exposure has only one model, no documentation should be selected for the top level exposure object - instead, associate the documentation with the model file.

A manual fix can be done by manually editing out the documentation and removing it.

I have since done that.
